<a href="https://colab.research.google.com/github/Deekshashivalingu/machine_learning_lab/blob/master/neuralnetworks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
x=np.array(([2,9],[1,5],[3,6]), dtype=float)
y = np.array(([92],[86],[89]), dtype=float)
#print(X),k
deno=np.amax(x,axis=0)
#print(aa)
x=x/deno
y=y/100
print(x)
print(y)

[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]


In [0]:
#Sigmoid function
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [0]:
#derivative of sigmoid function
def derivatives_sigmoid(x):  #[0.84,0.76,0.78]
  return x * (1 - x)

In [0]:
#variable initialization
iteration=1000  #setting training iterations
error_rate = 0.1  #setting learning rate-error rate
inputlayer_neurons=2 #number of features in data set
hiddenlayer_neurons=3 #number of hidden layers neurons
output_neurons=1  #number of neurons at output layer

In [0]:
weight_hidden=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
#print(weight_hidden)
bias_hidden=np.random.uniform(size=(1,hiddenlayer_neurons))
#print("bias value",bias_hidden)
weight_output=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bias_output=np.random.uniform(size=(1,output_neurons))

In [0]:
for i in range(iteration):
  hidden_input=np.dot(x,weight_hidden)  #h1=w1*x1+w2*x2+w3x3
  hidden_input=hidden_input + bias_hidden
  output_hidden_layer=sigmoid(hidden_input)
  #print(output_hidden_layer)
  actual_output=np.dot(output_hidden_layer,weight_output)+bias_output
  y_output=sigmoid(actual_output)
  #print("predicted output",y_output)
  
  #backpropagation
  EO=y-y_output
  outgrad=derivatives_sigmoid(y_output)
  d_output=EO*outgrad
  EH=d_output.dot(weight_output.T)
  hiddengrad=derivatives_sigmoid(output_hidden_layer)
  d_hiddenlayer=EH*hiddengrad
  
  weight_output+=output_hidden_layer.T.dot(d_output)*error_rate
  weight_hidden+=x.T.dot(d_hiddenlayer)*error_rate
  
print("Input: \n"+str(x))
print("Actual output: \n"+str(y))
print("Predicted output: \n",y_output)

Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted output: 
 [[0.89466619]
 [0.87867618]
 [0.89594816]]
